name: Merge upstream branches
on:
  schedule:
    - cron:  '10 11 * * *'
  workflow_dispatch:
  push:
    branches:
      - master  # 只有推送到 `master` 分支时才触发

jobs:
  merge:
    runs-on: ubuntu-latest
    
    steps:
      - name: Merge upstream
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git config --global credential.helper store
          git clone https://${{ secrets.PAT_TOKEN }}@github.com/tanquan/pingtunnel.git tmp
          cd tmp
          git remote add upstream https://${{ secrets.PAT_TOKEN }}@github.com/esrrhs/pingtunnel.git
          git fetch upstream
          git merge upstream/master
          git push origin master
